In [1]:
#BatchNormalization을 이용해 loss를 줄이고 accuracy를 높일 수 있다.

In [2]:
#기존에 Boston 프로젝트 값 불러오기###################################################################################################

In [6]:
import pandas as pd
import tensorflow as tf

path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(path)

In [7]:
indep = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax','ptratio', 'b', 'lstat']]
dep = boston[['medv']]

print(indep.shape, dep.shape)

(506, 13) (506, 1)


In [14]:
x1 = tf.keras.layers.Input(shape = [13])

H1 = tf.keras.layers.Dense(8, activation = 'swish')(x1)
H1 = tf.keras.layers.Dense(8, activation = 'swish')(H1)
H1 = tf.keras.layers.Dense(8, activation = 'swish')(H1)

y1 = tf.keras.layers.Dense(1)(H1)

model1 = tf.keras.models.Model(x1,y1)
model1.compile(loss = 'mse')

In [15]:
model1.fit(indep, dep, epochs = 1000, verbose = 0)
model1.fit(indep, dep, epochs = 10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 11.3267
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1060
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1900
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 10.9428
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 12.8536
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 11.5670
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 11.0643
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 11.8028
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 11.6451
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 12.3137


In [16]:
model1.predict(indep[0:5])

array([[31.985466],
       [23.204327],
       [29.389824],
       [33.65479 ],
       [30.200493]], dtype=float32)

In [4]:
####################################################################################################################################

# loss값이 일정구간에서 더이상 내려가지 않음을 알 수 있다.

In [5]:
# BatchNormalization 이용하기

## activation 함수를 분리 한 후 적용해주는 게 효과가 높다

In [18]:
x2 = tf.keras.layers.Input(shape = [13])

H2 = tf.keras.layers.Dense(8)(x2)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

H2 = tf.keras.layers.Dense(8)(H2)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

H2 = tf.keras.layers.Dense(8)(H2)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

y2 = tf.keras.layers.Dense(1)(H2)

model2 = tf.keras.models.Model(x2,y2)
model2.compile(loss = 'mse')

In [20]:
model2.fit(indep, dep, epochs=1000, verbose = 0)
model2.fit(indep, dep, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 9.3483
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 9.8844
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 8.5336
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 9.6101
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 9.8202
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 9.4240
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 10.3436
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 8.9533
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 9.1740
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 8.7111


In [21]:
# 로스값을 더 낮출 수 있음.

In [22]:
########################################################################################################################################

In [23]:
#iris 모델에도 적용 가능하다.

In [31]:
import tensorflow as tf
import pandas as pd

path = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
iris = pd.read_csv(path)

print(iris.head())
print(iris.columns)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [32]:
#원핫인코딩
iris = pd.get_dummies(iris)
print(iris.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [33]:
indep = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep =  iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(indep.shape)
print(dep.shape)

(150, 4)
(150, 3)


In [34]:
X = tf.keras.layers.Input(4)

H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(10, activation='swish')(H)
H = tf.keras.layers.Dense(10, activation='swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_23 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_24 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_25 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_26 (Dense)             (None, 3)                 33        
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(indep, dep, epochs=1000, verbose=0)
model.fit(indep, dep, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0442 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0392 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0490 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0492 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0502 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0454 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0541 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0435 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0464 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0405 - accuracy: 0.9800


In [ ]:
print(model.predict(indep[-5:]))
print(dep[-5:])

[[1.04860590e-06 9.74128917e-02 9.02586102e-01]
 [6.82622249e-06 2.09593192e-01 7.90399969e-01]
 [3.74266824e-06 1.65425837e-01 8.34570467e-01]
 [1.06510768e-07 2.27421690e-02 9.77257669e-01]
 [3.59991645e-06 1.20750204e-01 8.79246175e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [24]:
#히든레이어 없이는 약 300번의 학습을 통해 정확한 예측(정확성 95%)
#노드 10개의 히든레이어 3개 추가한 학습 결과 : epochs=100의 fit 1회만으로 정확성 98% 확보

In [25]:
#하지만 여전히 100%까지 올라가지 않음을 알 수 있다.

In [26]:
## BatchNormalization 적용

In [36]:
BX = tf.keras.layers.Input(shape=[4])

BH = tf.keras.layers.Dense(10)(BX)
BH = tf.keras.layers.BatchNormalization()(BH)
BH = tf.keras.layers.Activation('swish')(BH)

BH = tf.keras.layers.Dense(10)(BH)
BH = tf.keras.layers.BatchNormalization()(BH)
BH = tf.keras.layers.Activation('swish')(BH)

BH = tf.keras.layers.Dense(10)(BH)
BH = tf.keras.layers.BatchNormalization()(BH)
BH = tf.keras.layers.Activation('swish')(BH)

BY = tf.keras.layers.Dense(3, activation='softmax')(BH)

Bmodel = tf.keras.models.Model(BX, BY)
Bmodel.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

Bmodel.summary()

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 4)]               0         
_________________________________________________________________
dense_27 (Dense)             (None, 10)                50        
_________________________________________________________________
batch_normalization_10 (Batc (None, 10)                40        
_________________________________________________________________
activation_9 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 10)                110       
_________________________________________________________________
batch_normalization_11 (Batc (None, 10)                40        
_________________________________________________________________
activation_10 (Activation)   (None, 10)                0   

In [46]:
Bmodel.fit(indep, dep, epochs=1000, verbose=0)
Bmodel.fit(indep, dep, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0184 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0097 - accuracy: 1.0000
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0217 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0195 - accuracy: 0.9933
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0429 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0408 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0084 - accuracy: 0.9933
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0032 - accuracy: 1.0000


In [47]:
#loss값도 32bp로, accuracy값도 100%로 향상