In [ ]:
import tensorflow as tf
import pandas as pd

path = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
iris = pd.read_csv(path)

print(iris.head())
print(iris.columns)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
#원핫인코딩
iris = pd.get_dummies(iris)
print(iris.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
indep = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep =  iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(indep.shape)
print(dep.shape)

(150, 4)
(150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(10, activation='swish')(H)
H = tf.keras.layers.Dense(10, activation='swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_9 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_10 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 33        
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(indep, dep, epochs = 100)

Epoch 1/100
5/5 [==============================] - 1s 2ms/step - loss: 1.2350 - accuracy: 0.3408
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1018 - accuracy: 0.5226
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0606 - accuracy: 0.5781
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9721 - accuracy: 0.6197
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9528 - accuracy: 0.6082
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8987 - accuracy: 0.6601
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8872 - accuracy: 0.6609
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8439 - accuracy: 0.7361
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8265 - accuracy: 0.7289
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8033 - accuracy: 0.7298
Epoch 11/100
5/5 [===========

In [ ]:
print(model.predict(indep[-5:]))
print(dep[-5:])

[[1.04860590e-06 9.74128917e-02 9.02586102e-01]
 [6.82622249e-06 2.09593192e-01 7.90399969e-01]
 [3.74266824e-06 1.65425837e-01 8.34570467e-01]
 [1.06510768e-07 2.27421690e-02 9.77257669e-01]
 [3.59991645e-06 1.20750204e-01 8.79246175e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
#히든레이어 없이는 약 300번의 학습을 통해 정확한 예측(정확성 95%)
#노드 10개의 히든레이어 3개 추가한 학습 결과 : epochs=100의 fit 1회만으로 정확성 98% 확보