In [1]:
import pandas as pd
import tensorflow as tf

In [6]:
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
print(iris.head())
print(iris.columns)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [13]:
#원핫인코딩 : 범주형자료인 품종을 숫자형자료로 변환하는 과정
incoding = pd.get_dummies(iris)
print(incoding.head())
print(incoding.columns)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [14]:
#독립/종속변수 값 불러오기
indep = incoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep = incoding[['품종_setosa', '품종_versicolor',
       '품종_virginica']]

print(indep.shape)
print(dep.shape)

(150, 4)
(150, 3)


In [15]:
x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy',
              metrics = 'accuracy')

In [24]:
model.fit(indep, dep, epochs=1000, verbose=0)

In [30]:
#상단 5개 자료를 통한 검증
print(model.predict(indep[0:5]))
print(dep[0:5])

[[9.9959117e-01 4.0883708e-04 9.5953130e-09]
 [9.9820006e-01 1.7998074e-03 1.0004247e-07]
 [9.9914753e-01 8.5247977e-04 3.9313157e-08]
 [9.9760169e-01 2.3980692e-03 1.9622013e-07]
 [9.9966514e-01 3.3484280e-04 7.7767011e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [33]:
#하단 5개 자료를 통한 검증
print(model.predict(indep[-5:]))
print(dep[-5:])

[[9.5659189e-08 9.1585301e-02 9.0841454e-01]
 [3.3652327e-07 1.7415011e-01 8.2584953e-01]
 [5.7045992e-07 1.9768332e-01 8.0231613e-01]
 [6.7937087e-08 6.2989414e-02 9.3701047e-01]
 [1.3709312e-06 2.3519956e-01 7.6479906e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [34]:
#가중치 산출 (각 품종에 대한 가중치가 행렬의 형태로 나와있으며, 첫 열은 setosa / 두번째열은 versicolor / 세번째 열은 virginica 에 대한 확률값 산출에 대한 가중치가 나옴.)
model.get_weights()

[array([[ 1.0181247 ,  0.3254572 , -0.83136606],
        [ 3.206747  ,  0.5167901 , -0.7448877 ],
        [-3.9697807 , -0.48200506,  1.1757843 ],
        [-4.555031  , -0.70573694,  3.0441234 ]], dtype=float32),
 array([ 2.0343575,  1.5272812, -1.8877239], dtype=float32)]